services:
  web:
    image: app-test:latest  # Use a imagem com a tag 'latest'
    build: .
    ports:
      - "8007:8007"
    networks:
      - he_docker_network
    container_name: app-test
    
networks:
  he_docker_network:
    external: true